spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatStore?createDatabaseIfNotExist=true
    username: root
    password: root
    initialization-mode: always
  data:
    redis:
      repositories:
        enabled: true
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

websocket:
  endpoint: /ws
  appPrefix: /chatroom
  topic: /topic/
  queue: /queue/

app:
  chat:
    relay:
      host: localhost
      port: 61613

