spring:
  # Hibernate configuration
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true

  # Datasource configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: postgres
    initialization-mode: always

  session:
    store-type: redis

  # Redis configuration properties
  redis:
    host: localhost
    port: 6379

  # Spring Data Redis repository properties
  data:
    redis:
      repositories:
        enabled: true

  messages:
    cache-duration: 0
  rabbitmq:
    addresses:
    port: 5672

# Server session properties
server:
  servlet:
    session:
      timeout: 1m

# Web socket properties
websocket:
  endpoint: /ws
  appPrefix: /chatroom
  topic: /topic/
  queue: /queue/

# Application chat properties
app:
  chat:
    relay:
      host: localhost
      port: 61613


jwt:
  secretKey: JwtSecretKey
  expirationTimeMs: 604800000
header:
  name: Authorization
  type: "Bearer "